### ISSUE TITLE
Actor vs. Agent

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-remarks#3]
In xAPI the Actor property can take an Agent (or Group) object. Agents can also be the object of the statement and can appear in the context.instructor property. 

People often get mixed up and I myself often find myself using the wrong word and having to correct it!

In your syntax, you've used Agent where I think you mean Actor.

**Comment by ty-** [comment]
Yeah, I think the mixup happened because the syntax was originally only going to support Actor objectType Agent, but slowly the scope of this project is growing as I share it with others and receive feedback. I've updated Agent to Actor for the first part of the Remark / Statement.
