### ISSUE TITLE
Single letter properties too mysterious (opinion!)

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-remarks#5]
I really like the premise of this!

My concern is that in the current format, it's too complex for somebody not familiar with Remarks to understand the statement. As I understand it, the purpose of this is human readability, so if somebody has to read this specification in order to read remarks IMHO it has failed. 

I believe this could be resolved relatively simply by using full words for result and context properties and by including hints in the score object as to what the values represent, rather than a list. E.g. (45, 0-100 ,45%)

Attachments should also be kept simple - maybe just a description of the Attachment and thats it.

**Comment by ty-** [comment]
I've given this some thought and after seeing it in practice at the IoT xAPI Hackathon, it does pose an unecessary learning curve. Single letter properties are an over optimization.

However, I'll have to rewrite the parser logic a bit to handle the full words. When I have some time to put into this again I will address this.

**Comment by ty-** [comment]
groundwork is laid, all future keys will use the full names for properties and I will phase out the single characters.
