### ISSUE TITLE
some symbol may not be converted correctly

### ISSUE THREAD

**Issue by leaverij** [adlnet/xapi-remarks#6]
Just a small issue. There is minor error in  remarks in bulk here:

http://adlnet.github.io/xapi-remarks/examples/example-1.html

When the statement contains 「“」, it can not be converted correctly. It should be 「"」.

For example, see p: [“page 9”] in this statement remark:

tyler@example.com <highlighted> <paragraph 6> ( r: "need help" ) { p: [“page 9”], g: ["chapter 2", "cool book", "cool class"] }

**Comment by ty-** [comment]
Thanks for catching that, I must have made that error when copying over examples from a Google Doc.
